//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Phrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Phrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftPro.Wasilni.Domain.Models.Resources.Phrases", typeof(Phrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تأكيد الحساب بالفعل.
        /// </summary>
        public static string AccountAlreadyConfirmed {
            get {
                return ResourceManager.GetString("AccountAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الحساب الجديدة مطابقة للبيانات الحالية. يُرجى إجراء تعديل..
        /// </summary>
        public static string AccountDataNoChanged {
            get {
                return ResourceManager.GetString("AccountDataNoChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحساب ليس مالك لباصات.
        /// </summary>
        public static string AccountIsNotOwner {
            get {
                return ResourceManager.GetString("AccountIsNotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحساب غير مؤكد..
        /// </summary>
        public static string AccountNotConfirmed {
            get {
                return ResourceManager.GetString("AccountNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحساب غير موجود.
        /// </summary>
        public static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحساب غير مسجل.
        /// </summary>
        public static string AccountNotRegistered {
            get {
                return ResourceManager.GetString("AccountNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هناك سائق آخر على الباص..
        /// </summary>
        public static string AssignedOtherDriver {
            get {
                return ResourceManager.GetString("AssignedOtherDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباص ما عم يعبي.
        /// </summary>
        public static string BusNotFilling {
            get {
                return ResourceManager.GetString("BusNotFilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباص غير موجود.
        /// </summary>
        public static string BusNotFound {
            get {
                return ResourceManager.GetString("BusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباص مانه عالطريق.
        /// </summary>
        public static string BusNotOnRoad {
            get {
                return ResourceManager.GetString("BusNotOnRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود المرسل غير متطابق مع هذا الكود.
        /// </summary>
        public static string CannotMatchCode {
            get {
                return ResourceManager.GetString("CannotMatchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة مضافة بالفعل.
        /// </summary>
        public static string CityAlreadyExists {
            get {
                return ResourceManager.GetString("CityAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تعديل المدينة.
        /// </summary>
        public static string CityCannotUpdated {
            get {
                return ResourceManager.GetString("CityCannotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات المدينة المسجلة هي نفسها المعلومات المدخلة.
        /// </summary>
        public static string CityDataNoChanged {
            get {
                return ResourceManager.GetString("CityDataNoChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة غير موجودة.
        /// </summary>
        public static string CityNotFound {
            get {
                return ResourceManager.GetString("CityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنسق موجود بالفعل..
        /// </summary>
        public static string CoordinatorAlreadyExists {
            get {
                return ResourceManager.GetString("CoordinatorAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنسق غير موجود..
        /// </summary>
        public static string CoordinatorNotFound {
            get {
                return ResourceManager.GetString("CoordinatorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السائق موجود بالفعل.
        /// </summary>
        public static string DriverAlreadyExists {
            get {
                return ResourceManager.GetString("DriverAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السائق غير موجود.
        /// </summary>
        public static string DriverNotFound {
            get {
                return ResourceManager.GetString("DriverNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحساب غير مصرح له بالدخول.
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة المصدر هي نفسها المينة الوجهة.
        /// </summary>
        public static string FromIsSameTo {
            get {
                return ResourceManager.GetString("FromIsSameTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سأكون سعيدا بتعاوني معك.
        /// </summary>
        public static string IGladToBeWithYouSir {
            get {
                return ResourceManager.GetString("IGladToBeWithYouSir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في معرف الحساب.
        /// </summary>
        public static string InvalidAccountId {
            get {
                return ResourceManager.GetString("InvalidAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسم العربي غير صالح.
        /// </summary>
        public static string InvalidArabicName {
            get {
                return ResourceManager.GetString("InvalidArabicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف الباص غير صالح.
        /// </summary>
        public static string InvalidBusId {
            get {
                return ResourceManager.GetString("InvalidBusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الباص غير صالح.
        /// </summary>
        public static string InvalidBusType {
            get {
                return ResourceManager.GetString("InvalidBusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المدينة المصدر غير صالح.
        /// </summary>
        public static string InvalidCityFromId {
            get {
                return ResourceManager.GetString("InvalidCityFromId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المدينة غير صالح.
        /// </summary>
        public static string InvalidCityId {
            get {
                return ResourceManager.GetString("InvalidCityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المدينة الوجهه غير صالح.
        /// </summary>
        public static string InvalidCityToId {
            get {
                return ResourceManager.GetString("InvalidCityToId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود غير صالح.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في اللون.
        /// </summary>
        public static string InvalidColor {
            get {
                return ResourceManager.GetString("InvalidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التكلفة غير صالحة.
        /// </summary>
        public static string InvalidCost {
            get {
                return ResourceManager.GetString("InvalidCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسم الإنكليزي غير صالح.
        /// </summary>
        public static string InvalidEnglishName {
            get {
                return ResourceManager.GetString("InvalidEnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوقت المقدر للرحلة غير صالح.
        /// </summary>
        public static string InvalidEstimatedTime {
            get {
                return ResourceManager.GetString("InvalidEstimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفلتر غير صالح.
        /// </summary>
        public static string InvalidFilter {
            get {
                return ResourceManager.GetString("InvalidFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في المدينة المصدر.
        /// </summary>
        public static string InvalidFrom {
            get {
                return ResourceManager.GetString("InvalidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في معرف المدينة المصدر.
        /// </summary>
        public static string InvalidFromId {
            get {
                return ResourceManager.GetString("InvalidFromId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعرف غير صالج.
        /// </summary>
        public static string InvalidId {
            get {
                return ResourceManager.GetString("InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف الحساب أو الرمز غير صالح..
        /// </summary>
        public static string InvalidIdOrRefreshToken {
            get {
                return ResourceManager.GetString("InvalidIdOrRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في معرف الخط.
        /// </summary>
        public static string InvalidLineId {
            get {
                return ResourceManager.GetString("InvalidLineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع غير صالح.
        /// </summary>
        public static string InvalidLocation {
            get {
                return ResourceManager.GetString("InvalidLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد التذاكر غير صالح.
        /// </summary>
        public static string InvalidNumberOfTickets {
            get {
                return ResourceManager.GetString("InvalidNumberOfTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المالك غير صالح.
        /// </summary>
        public static string InvalidOwnerId {
            get {
                return ResourceManager.GetString("InvalidOwnerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النسبة يجب أن تكون بين 0 و 100..
        /// </summary>
        public static string InvalidOwnerPercent {
            get {
                return ResourceManager.GetString("InvalidOwnerPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الصفحة يجب أن يكون موجب.
        /// </summary>
        public static string InvalidPageNumber {
            get {
                return ResourceManager.GetString("InvalidPageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم الصفحة يجب أن يكون موجب.
        /// </summary>
        public static string InvalidPageSize {
            get {
                return ResourceManager.GetString("InvalidPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة السر غير صالحة.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم غير صالح..
        /// </summary>
        public static string InvalidPhonenumber {
            get {
                return ResourceManager.GetString("InvalidPhonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النمرة غير صالحة.
        /// </summary>
        public static string InvalidPlate {
            get {
                return ResourceManager.GetString("InvalidPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إنزال الرحلة بعد 45 ساعة من التاريخ الحالي.
        /// </summary>
        public static string InvalidQuitTime {
            get {
                return ResourceManager.GetString("InvalidQuitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود غير صالح.
        /// </summary>
        public static string InvalidRefreshToken {
            get {
                return ResourceManager.GetString("InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في المدينة الهدف.
        /// </summary>
        public static string InvalidTo {
            get {
                return ResourceManager.GetString("InvalidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في المدينة الهدف.
        /// </summary>
        public static string InvalidToId {
            get {
                return ResourceManager.GetString("InvalidToId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف الرحلة غير صالح.
        /// </summary>
        public static string InvalidTripId {
            get {
                return ResourceManager.GetString("InvalidTripId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم غير صالح.
        /// </summary>
        public static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دعوة لتكون سائق على باص معي.
        /// </summary>
        public static string InviteToBeDriverOnBus {
            get {
                return ResourceManager.GetString("InviteToBeDriverOnBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخط موجود مسبقا.
        /// </summary>
        public static string LineAlreadyExists {
            get {
                return ResourceManager.GetString("LineAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الخط لم تتغير.
        /// </summary>
        public static string LineDataNoChange {
            get {
                return ResourceManager.GetString("LineDataNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخط غير موجود.
        /// </summary>
        public static string LineNotFound {
            get {
                return ResourceManager.GetString("LineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إعادة تسجيل الدخول.
        /// </summary>
        public static string LoginAgain {
            get {
                return ResourceManager.GetString("LoginAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور القديمة لا تتطابق مع كلمة المرور الحالية..
        /// </summary>
        public static string MatchOld {
            get {
                return ResourceManager.GetString("MatchOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم تغيير كلمة المرور الجديدة..
        /// </summary>
        public static string NewPasswordNoChanged {
            get {
                return ResourceManager.GetString("NewPasswordNoChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس سائقا من الأصل.
        /// </summary>
        public static string NotDriver {
            get {
                return ResourceManager.GetString("NotDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحساب غير موجود.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المالك مطابق لمعرف السائق.
        /// </summary>
        public static string OwnIdEqualDriverIdRequest {
            get {
                return ResourceManager.GetString("OwnIdEqualDriverIdRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم موجود.
        /// </summary>
        public static string PhonenumberAlreadyExsits {
            get {
                return ResourceManager.GetString("PhonenumberAlreadyExsits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النمرة مسجلة مسبقا.
        /// </summary>
        public static string PlateAlreadyExists {
            get {
                return ResourceManager.GetString("PlateAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلب موجود مسبقا.
        /// </summary>
        public static string RequestAlreadyExists {
            get {
                return ResourceManager.GetString("RequestAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلب مرفوض بالفعل.
        /// </summary>
        public static string RequestAlreadyRejected {
            get {
                return ResourceManager.GetString("RequestAlreadyRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلب غير موجود.
        /// </summary>
        public static string RequestNotFound {
            get {
                return ResourceManager.GetString("RequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلب ليس في حالة الانتظار.
        /// </summary>
        public static string RequestNotPending {
            get {
                return ResourceManager.GetString("RequestNotPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلب موجود لسائق أخر.
        /// </summary>
        public static string RequestToAnotherDriver {
            get {
                return ResourceManager.GetString("RequestToAnotherDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد قمت بإرسال الرمز أكثر من مرة, الرجاح المحاولة بعد مدة من الزمن..
        /// </summary>
        public static string SendCodeMoreTime {
            get {
                return ResourceManager.GetString("SendCodeMoreTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد سائق على هذا الباص من الأساس.
        /// </summary>
        public static string ThereIsNoDriverOnThisBus {
            get {
                return ResourceManager.GetString("ThereIsNoDriverOnThisBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التكتات المراد حجزها تتخطى حدود الأماكن الفارغة.
        /// </summary>
        public static string TicketsMoreThanEmptyPlaces {
            get {
                return ResourceManager.GetString("TicketsMoreThanEmptyPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هناك رحلة موجودة بالفعل.
        /// </summary>
        public static string TripAlreadyExists {
            get {
                return ResourceManager.GetString("TripAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرحلة قد مشيت بالفعل.
        /// </summary>
        public static string TripAlreadyGone {
            get {
                return ResourceManager.GetString("TripAlreadyGone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرحلة غير موجودة.
        /// </summary>
        public static string TripNotFound {
            get {
                return ResourceManager.GetString("TripNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرحلة ستمضي في غضون 15 دقيقة.
        /// </summary>
        public static string TripWillGo {
            get {
                return ResourceManager.GetString("TripWillGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحساب غير مسجل.
        /// </summary>
        public static string Unauthorize {
            get {
                return ResourceManager.GetString("Unauthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة السر أو المستخدم غير صحيحة.
        /// </summary>
        public static string UsernameOrPasswordIsInvalid {
            get {
                return ResourceManager.GetString("UsernameOrPasswordIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انت لم ترسل كود اصلا.
        /// </summary>
        public static string YouHaveNotSentCode {
            get {
                return ResourceManager.GetString("YouHaveNotSentCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف هذا السجل لأنه مستخدم من قبل كيانات أخرى.
        /// </summary>
        public static string RecordInUse {
            get {
                return ResourceManager.GetString("RecordInUse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم الخط غير صالح.
        /// </summary>
        public static string InvalidLineName {
            get {
                return ResourceManager.GetString("InvalidLineName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to خط العرض يجب أن يكون بين -90 و 90.
        /// </summary>
        public static string InvalidLatitude {
            get {
                return ResourceManager.GetString("InvalidLatitude", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to خط الطول يجب أن يكون بين -180 و 180.
        /// </summary>
        public static string InvalidLongitude {
            get {
                return ResourceManager.GetString("InvalidLongitude", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to معرف النقطة غير صالح.
        /// </summary>
        public static string InvalidPointId {
            get {
                return ResourceManager.GetString("InvalidPointId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to النقطة غير موجودة.
        /// </summary>
        public static string PointNotFound {
            get {
                return ResourceManager.GetString("PointNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب إضافة نقطة واحدة على الأقل.
        /// </summary>
        public static string PointsRequired {
            get {
                return ResourceManager.GetString("PointsRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الباص في رحلة نشطة بالفعل.
        /// </summary>
        public static string BusAlreadyActive {
            get {
                return ResourceManager.GetString("BusAlreadyActive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to هذا الباص غير مخصص لك.
        /// </summary>
        public static string NotYourBus {
            get {
                return ResourceManager.GetString("NotYourBus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرحلة منتهية بالفعل.
        /// </summary>
        public static string TripAlreadyEnded {
            get {
                return ResourceManager.GetString("TripAlreadyEnded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to القيمة يجب أن تكون 1 أو -1 فقط.
        /// </summary>
        public static string InvalidDelta {
            get {
                return ResourceManager.GetString("InvalidDelta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الحجز غير موجود.
        /// </summary>
        public static string BookingNotFound {
            get {
                return ResourceManager.GetString("BookingNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لديك حجز نشط بالفعل على هذه الرحلة.
        /// </summary>
        public static string AlreadyBooked {
            get {
                return ResourceManager.GetString("AlreadyBooked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to هذا الحجز ليس لك.
        /// </summary>
        public static string NotYourBooking {
            get {
                return ResourceManager.GetString("NotYourBooking", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرحلة غير نشطة.
        /// </summary>
        public static string TripNotActive {
            get {
                return ResourceManager.GetString("TripNotActive", resourceCulture);
            }
        }

        public static string InvalidReportType {
            get {
                return ResourceManager.GetString("InvalidReportType", resourceCulture);
            }
        }

        public static string InvalidDateRange {
            get {
                return ResourceManager.GetString("InvalidDateRange", resourceCulture);
            }
        }
    }
}
