//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Title {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Title() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftPro.Wasilni.Domain.Models.Resources.Title", typeof(Title).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم قبول الطلب من قبل السائق.
        /// </summary>
        public static string AcceptRequestByDriver {
            get {
                return ResourceManager.GetString("AcceptRequestByDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف الحساب.
        /// </summary>
        public static string AccountId {
            get {
                return ResourceManager.GetString("AccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم بالعربي.
        /// </summary>
        public static string ArabicName {
            get {
                return ResourceManager.GetString("ArabicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف الباص.
        /// </summary>
        public static string BusId {
            get {
                return ResourceManager.GetString("BusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الباص.
        /// </summary>
        public static string BusType {
            get {
                return ResourceManager.GetString("BusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المدينة المصدر.
        /// </summary>
        public static string CityFromId {
            get {
                return ResourceManager.GetString("CityFromId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المدينة.
        /// </summary>
        public static string CityId {
            get {
                return ResourceManager.GetString("CityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المدينة الوجهه.
        /// </summary>
        public static string CityToId {
            get {
                return ResourceManager.GetString("CityToId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللون.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التكلفة.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم بالإنكليزي.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوقت المقدر.
        /// </summary>
        public static string EstimatedTime {
            get {
                return ResourceManager.GetString("EstimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فلتر.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة المصدر.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المدينة المصدر.
        /// </summary>
        public static string FromId {
            get {
                return ResourceManager.GetString("FromId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعرف.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف الخط.
        /// </summary>
        public static string LineId {
            get {
                return ResourceManager.GetString("LineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة السر الجديدة.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد التذاكر.
        /// </summary>
        public static string NumberOfTickets {
            get {
                return ResourceManager.GetString("NumberOfTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة السر القديمة.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المالك.
        /// </summary>
        public static string OwnerId {
            get {
                return ResourceManager.GetString("OwnerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسبه المالك.
        /// </summary>
        public static string OwnerPercent {
            get {
                return ResourceManager.GetString("OwnerPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الصفحة.
        /// </summary>
        public static string PageNumber {
            get {
                return ResourceManager.GetString("PageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم الصفحة.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة السر.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string Phonenumber {
            get {
                return ResourceManager.GetString("Phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النمرة.
        /// </summary>
        public static string Plate {
            get {
                return ResourceManager.GetString("Plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود.
        /// </summary>
        public static string RefreshToken {
            get {
                return ResourceManager.GetString("RefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال طلب لتكون سائق.
        /// </summary>
        public static string SendRequestToDriver {
            get {
                return ResourceManager.GetString("SendRequestToDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة الهدف.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المدينة الوجهة.
        /// </summary>
        public static string ToId {
            get {
                return ResourceManager.GetString("ToId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف الرحلة.
        /// </summary>
        public static string TripId {
            get {
                return ResourceManager.GetString("TripId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرحلة ستمضي.
        /// </summary>
        public static string TripWillGo {
            get {
                return ResourceManager.GetString("TripWillGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسم.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم الخط.
        /// </summary>
        public static string LineName {
            get {
                return ResourceManager.GetString("LineName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to خط العرض.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to خط الطول.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to معرف النقطة.
        /// </summary>
        public static string PointId {
            get {
                return ResourceManager.GetString("PointId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to النقاط.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to التغيير.
        /// </summary>
        public static string Delta {
            get {
                return ResourceManager.GetString("Delta", resourceCulture);
            }
        }
    }
}
